name: yaml_magic
description: A Dart+Flutter package for manipulating YAML files, providing utilities to load, add, modify / edit, and save YAML documents.
version: 1.0.4+1
repository: https://github.com/itisnajim/yaml_magic

environment:
  sdk: ^3.0.5

dependencies:
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
