name: yaml_magic
description: A Dart+Flutter package for manipulating YAML files, providing utilities to load, add, modify / edit, and save YAML documents.
version: 1.0.6
repository: https://github.com/itisnajim/yaml_magic

environment:
  sdk: ^3.0.5

dependencies:
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.0
